# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    env:
      ProductName: XPP
      ProductNameWithEdition: 'XPP'
      AppSigningEmail : app-signing@sdl.com
      DotNetVersion: '.Net Framework 4.8'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install docfx
        run: |
          dotnet tool install -g docfx

      - name: build _site
        run: docfx.exe build docfx.json

      # Runs a set of commands using the runners shell
      #- name: commit to gh-pages
      #  run: bash releaseDocs.sh $GITHUB_ACTOR ${{ secrets.GITHUB_TOKEN }}
      - shell: pwsh
        run: |
          .\releaseDocs.ps1 "$GITHUB_ACTOR" "${{ secrets.GITHUB_TOKEN }}"
        if: github.event_name != 'pull_request'
